---
- name: Gather and display fact information
  hosts: ios
  gather_facts: false
  tasks:
    - name: Gather IOS facts
      cisco.ios.ios_facts:
        gather_network_resources:
          - vlans

    - name: Print facts
      ansible.builtin.debug:
        var: ansible_facts
